# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'games/libkdegames': '@same'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
